#line 2 "lex.yy.c"

#line 4 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 16
#define YY_END_OF_BUFFER 17
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_acclist[213] =
    {   0,
       17,   15,   16,   14,   15,   16,   13,   16,   13,   15,
       16,   15,   16,    4,   14,   15,   16,    1,   15,   16,
       12,   15,   16,   15,   16,   15,   16,   11,   15,   16,
       15,   16,    9,   15,   16,    7,   15,   16,    7,   15,
       16,    2,   15,   16,   12,   15,   16,   12,   15,   16,
       12,   15,   16,   12,   15,   16,   12,   15,   16,    1,
       12,   15,   16,    1,   12,   15,   16,    1,   12,   15,
       16,    1,   12,   15,   16,    1,   12,   15,   16,   13,
        4,    1,    1,    1,   12,   12,   12,   12,   12,    7,
        8,    9,    9,    8,    7,    7,    7,   12,   12,   12,

     8198,   12,16390,   12,   12,    1,   12,    1,   12,    1,
       12,    1,   12,    1, 8198,   12,16390,    1,   12,    1,
       12,    3,    1,    1,   12,    9,    9,    9,    9,    8,
        7,    7,   12, 8198, 8198, 8198,   12, 8198,   12,   12,
     8197,   12,16389,    1,   12,    1,   12,    1,   12, 8198,
        1, 8198,   12,    1, 8198,   12,    1, 8198,   12,    1,
       12,    1, 8197,   12,16389,   10,   12, 8197,   12,16389,
     8197, 8197, 8197,   12, 8197,   12,    1,   12,    1, 8198,
       12,    1, 8198,   12,    1, 8197,   12,16389, 8197,    1,
     8197,   12,    1, 8197,   12,    1, 8197,   12,    8, 8198,

       12,16390,    1, 8198,   12,16390,    1, 8197,   12,    1,
     8197,   12
    } ;

static yyconst flex_int16_t yy_accept[145] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        4,    7,    9,   12,   14,   18,   21,   24,   26,   28,
       31,   33,   36,   39,   42,   45,   48,   51,   54,   57,
       60,   64,   68,   72,   76,   80,   81,   81,   82,   82,
       83,   84,   85,   86,   87,   88,   89,   90,   90,   90,
       91,   92,   93,   94,   95,   96,   97,   98,   98,   99,
      100,  101,  104,  105,  106,  106,  108,  110,  112,  114,
      118,  120,  122,  122,  122,  122,  122,  123,  124,  125,
      126,  126,  126,  127,  128,  129,  130,  131,  132,  133,
      134,  135,  136,  138,  140,  141,  144,  146,  148,  150,

      151,  154,  157,  160,  162,  166,  166,  166,  166,  166,
      166,  166,  166,  167,  167,  168,  171,  172,  173,  175,
      177,  179,  182,  185,  189,  190,  193,  196,  199,  199,
      199,  199,  200,  203,  207,  210,  213,  213,  213,  213,
      213,  213,  213,  213
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    7,    8,    9,    6,    6,   10,    6,
        6,    6,   11,   12,   13,   14,   15,   16,   17,   18,
       18,   18,   18,   18,   18,   19,   19,   20,   21,    6,
       22,    6,   23,    6,   24,   25,   26,   26,   27,   28,
       29,   29,   29,   29,   29,   30,   29,   31,   32,   29,
       29,   33,   34,   35,   36,   29,   29,   37,   38,   29,
       39,   40,   41,    6,   42,    6,   43,   44,   26,   26,

       45,   46,   29,   29,   29,   29,   29,   47,   29,   48,
       49,   29,   29,   50,   51,   52,   53,   29,   29,   54,
       55,   29,   56,    6,   57,   58,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[59] =
    {   0,
        1,    2,    3,    4,    5,    2,    2,    6,    5,    5,
        7,    4,    8,    8,    9,   10,   10,   10,   10,    2,
        4,    2,    5,   11,   11,   11,   11,   11,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,    2,    2,
       13,    8,   11,   11,   11,   11,   12,   12,   12,   12,
       12,   12,   12,   12,   12,    2,   14,    8
    } ;

static yyconst flex_int16_t yy_base[167] =
    {   0,
        0,   39,   97,  155,    0,    1,  212,    4,  273, 2048,
     2048, 2048,  243,    0,    4,  247,  215,  185,    0, 2048,
       11,   17,  292,   17, 2048,  345,  196,  189,  190,  197,
      402,  201,  194,  195,  202, 2048,  456,    5,  262,  273,
      471,  525,  255,  287,  294, 2048,    9,    0,  305,  321,
      472,   10,  573,  488,  502,   21,    0,  225,  231,    0,
      201,  631,  201,  265,  688,  745,    0,    0,  272,  803,
      277,  291,  540,  857,  911,  965, 2048,    0,    0,  460,
     1019,  266, 1067,    0,    0,    0,  552,  233,    0,  292,
        0, 1102,    0,    0,  208, 1157,    0,    0,  294, 1215,

     1250,    0,    0,  247, 1305,    0,    0,  551,    0, 1359,
     1413, 1467, 2048,  492,  273,    0,    0, 1502,    0,    0,
      287,    0,    0,    0, 1557, 1592,    0,    0,    0,    0,
     1643,  506,    0,    0,    0,    0,  859, 1697, 1751, 1805,
        0,    0, 2048, 1863,  257, 1873, 1884, 1890, 1898, 1907,
     1915,  269, 1921,  338, 1932, 1942, 1950, 1959, 1973, 1983,
      394, 1991, 2005, 2015, 2025, 2033
    } ;

static yyconst flex_int16_t yy_def[167] =
    {   0,
      144,  143,  143,  143,    3,    4,  144,    2,  143,  143,
      143,  143,  143,  145,  143,  146,  147,  143,  143,  143,
      143,  148,  143,  143,  143,  143,   26,   26,   26,   26,
      143,   31,   31,   31,   31,  143,  149,  143,  150,  151,
      151,  146,  147,  147,  147,  143,  147,  152,  143,  143,
      143,  148,  153,  143,  143,  143,  154,  155,  155,   26,
       26,  143,   26,   26,  143,  143,   66,   31,   31,  143,
       31,   31,  156,  157,  157,  149,  143,   41,   41,  147,
      158,  143,  153,  148,   83,   83,  143,  143,  154,   26,
      159,   62,   92,   62,   26,  143,   66,   66,   31,  143,

       70,  101,   70,   31,  143,   75,   75,  160,  161,  162,
      162,  158,  143,  143,   26,   96,  163,   96,  118,   96,
       31,  101,  101,  105,  143,  105,  126,  105,  111,  111,
      164,  143,   62,   70,  126,  126,  165,  166,  166,  164,
      139,  139,    0,  143,  143,  143,  143,  143,  143,  143,
      143,  143,  143,  143,  143,  143,  143,  143,  143,  143,
      143,  143,  143,  143,  143,  143
    } ;

static yyconst flex_int16_t yy_nxt[2107] =
    {   0,
      143,   11,   12,   13,   11,   38,   38,  143,   38,   38,
      143,  143,  143,   49,   84,   50,   50,   50,   50,   10,
       10,   10,   10,   25,   52,   25,   51,   51,   51,   51,
       54,   52,   50,   50,   50,   50,   88,   88,   14,   10,
       15,   12,   13,   15,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   16,   16,   16,   16,   16,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   14,   10,   10,
       10,   16,   16,   16,   16,   16,   16,   16,   16,   16,
       16,   16,   16,   16,   10,   10,   10,   10,   11,   12,

       13,   11,   10,   17,   10,   18,   10,   19,   20,   19,
       21,   22,   23,   24,   24,   24,   25,   10,   25,   10,
       26,   26,   26,   26,   27,   26,   26,   28,   26,   26,
       26,   29,   26,   26,   30,   14,   10,   10,   10,   26,
       26,   26,   27,   26,   28,   26,   26,   26,   29,   26,
       26,   30,   10,   10,   10,   10,   15,   12,   13,   15,
       10,   17,   10,   18,   10,   19,   20,   19,   21,   22,
       23,   24,   24,   24,   25,   10,   25,   10,   31,   31,
       31,   31,   32,   31,   31,   33,   31,   31,   31,   34,
       31,   31,   35,   14,   10,   10,   10,   31,   31,   31,

       32,   31,   33,   31,   31,   31,   34,   31,   31,   35,
       10,   10,   10,   11,   12,   13,   11,   44,   45,   61,
       62,   46,   63,   64,   69,   70,   58,   71,   72,   58,
       90,   25,   58,   25,  116,   58,   95,   62,   61,   63,
       48,   64,   70,   69,   71,   36,   72,   90,   88,   88,
       14,   39,  116,   95,   47,   40,   40,   44,   45,   40,
       40,   46,   41,   41,   41,   41,   39,   37,   37,   40,
       78,   78,  143,  124,   78,   78,  114,   39,  114,   81,
       81,   40,   40,  143,   78,   40,   40,  143,   40,   44,
       45,  124,  143,   46,   47,   40,   80,   45,   96,  133,

       46,   99,  143,   78,   40,   54,  143,   55,   55,   55,
       50,  143,  104,  134,   40,   96,   56,  133,   99,   78,
       51,   51,   51,   51,  105,  115,   47,  121,   57,  104,
       40,  134,  143,   47,   54,   56,   50,   50,   50,   50,
      143,  105,  115,  143,  121,   57,   58,   89,   89,   58,
       59,   59,  143,   59,   59,   59,  143,   59,   59,   59,
       59,   59,   59,   59,   59,  143,   59,   59,   60,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   59,   59,   59,   59,   60,   60,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,

       59,   59,   59,   58,  131,  131,   65,   59,   59,  143,
       66,   66,   59,  143,   66,   66,   59,   67,   67,   67,
       67,   59,  143,   59,   66,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   68,   68,
       59,   59,   59,   66,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   59,   59,   66,
       73,  143,   44,   45,   74,   74,   46,  143,   74,   74,
      143,   75,   75,   75,   75,   39,  143,  143,   74,   40,
       40,  143,  143,   40,   40,  143,  143,   51,   51,   51,
       51,  143,  143,   40,  143,  143,   77,   74,   82,   47,

      143,  143,  143,   87,   87,   87,   87,  132,  132,  132,
      132,  143,   40,   74,   82,   54,   82,   55,   55,   55,
       50,  132,  132,  132,  132,  143,  143,  143,   40,   39,
      143,  143,   82,   40,   40,  143,  143,   40,   40,  143,
       41,   41,   41,   41,   73,  143,  143,   40,  106,  106,
      143,  143,  106,  106,  143,  108,  143,  143,  143,  129,
      129,  143,  106,  129,  129,  143,   40,   87,   87,   87,
       87,  143,  143,  129,  143,  143,  143,  143,   82,  143,
      143,  106,   40,   83,  143,   83,   83,   84,   85,   85,
       85,   85,  129,  143,  143,  143,   82,  106,  143,  143,

      143,  143,  143,  143,  143,  143,  143,  143,  129,  143,
      143,  143,  143,  143,   83,  143,  143,  143,  143,  143,
      143,  143,  143,  143,  143,  143,  143,  143,  143,  143,
       83,   91,   92,  143,   91,   92,   93,   93,   91,   93,
       93,   93,   91,   93,   93,   93,   93,   93,   93,   93,
       93,   91,   93,   93,   94,   94,   94,   94,   94,   94,
       94,   94,   94,   94,   94,   94,   94,   94,   94,   93,
       93,   93,   93,   94,   94,   94,   94,   94,   94,   94,
       94,   94,   94,   94,   94,   94,   93,   93,   93,   58,
      143,  143,   65,   59,   59,  143,   97,   97,   59,  143,

       97,   97,   59,   98,   98,   98,   98,   59,  143,   59,
       97,   98,   98,   98,   98,   98,   98,   98,   98,   98,
       98,   98,   98,   98,   98,   98,   59,   59,   59,   97,
       98,   98,   98,   98,   98,   98,   98,   98,   98,   98,
       98,   98,   98,   59,   59,   97,   58,  143,  143,   65,
       59,   59,  143,   66,   66,   59,  143,   66,   66,   59,
       67,   67,   67,   67,   59,  143,   59,   66,   67,   67,
       67,   67,   67,   67,   67,   67,   67,   67,   67,   67,
       67,   67,   67,   59,   59,   59,   66,   67,   67,   67,
       67,   67,   67,   67,   67,   67,   67,   67,   67,   67,

       59,   59,   66,   91,   92,  143,   91,  100,   93,   93,
       91,  101,  101,   93,   91,  101,  101,   93,  102,  102,
      102,  102,   93,   91,   93,  101,  103,  103,  103,  103,
      103,  103,  103,  103,  103,  103,  103,  103,  103,  103,
      103,   93,   93,   93,  101,  103,  103,  103,  103,  103,
      103,  103,  103,  103,  103,  103,  103,  103,   93,   93,
      101,   73,  143,  137,  143,   74,   74,  141,  141,   74,
       74,  141,  141,  143,  143,  143,  143,  143,  143,   74,
      143,  141,  143,  143,  143,  143,  143,  143,  143,  143,
      143,  143,  143,  143,  143,  143,  143,   77,   74,  143,

      141,  143,  143,  143,  143,  143,  143,  143,  143,  143,
      143,  143,  143,  143,   74,   73,  141,  143,  143,   74,
       74,  143,  143,   74,   74,  143,  143,  143,  143,  143,
      143,  143,  143,   74,  143,  143,  143,  143,  143,  143,
      143,  143,  143,  143,  143,  143,  143,  143,  143,  143,
      143,   77,   74,  143,  143,  143,  143,  143,  143,  143,
      143,  143,  143,  143,  143,  143,  143,  143,   74,   73,
      143,  143,  143,   74,   74,  143,  143,   74,   74,  143,
       75,   75,   75,   75,  143,  143,  143,   74,  143,  143,
      143,  143,  143,  143,  143,  143,  143,  143,  143,  143,

      143,  143,  143,  143,  143,   77,   74,  143,  143,  143,
      143,  143,  143,  143,  143,  143,  143,  143,  143,  143,
      143,  143,   74,  108,  143,  143,  109,  110,  110,  143,
      143,  110,  110,  143,  111,  111,  111,  111,  143,  143,
      143,  110,  143,  143,  143,  143,  143,  143,  143,  143,
      143,  143,  143,  143,  143,  143,  143,  143,  143,  143,
      110,  143,  143,  143,  143,  143,  143,  143,  143,  143,
      143,  143,  143,  143,  143,  113,  110,   83,  143,   83,
       83,   84,   85,   85,   85,   85,  143,  143,  143,  143,
      143,  143,  143,  143,  143,  143,  143,  143,  143,  143,

      143,  143,  143,  143,  143,  143,  143,  143,   83,  143,
      143,  143,  143,  143,  143,  143,  143,  143,  143,  143,
      143,  143,  143,  143,   83,   93,   93,   93,   93,   93,
       93,   93,   93,   93,   93,   93,   93,   93,   93,   93,
      143,  143,  143,  143,   93,   93,   93,   93,   93,   93,
       93,   93,   93,   93,   93,   93,   93,  117,  118,  143,
      117,  118,  119,  119,  117,  119,  119,  119,  117,  119,
      119,  119,  119,  119,  119,  119,  119,  117,  119,  119,
      120,  120,  120,  120,  120,  120,  120,  120,  120,  120,
      120,  120,  120,  120,  120,  119,  119,  119,  119,  120,

      120,  120,  120,  120,  120,  120,  120,  120,  120,  120,
      120,  120,  119,  119,  119,   91,   92,  143,   91,  100,
       93,   93,   91,  122,  122,   93,   91,  122,  122,   93,
      123,  123,  123,  123,   93,   91,   93,  122,  123,  123,
      123,  123,  123,  123,  123,  123,  123,  123,  123,  123,
      123,  123,  123,   93,   93,   93,  122,  123,  123,  123,
      123,  123,  123,  123,  123,  123,  123,  123,  123,  123,
       93,   93,  122,  102,  102,  102,  102,  102,  102,  102,
      102,  102,  102,  102,  102,  102,  102,  102,  143,  143,
      143,  143,  102,  102,  102,  102,  102,  102,  102,  102,

      102,  102,  102,  102,  102,  117,  118,  143,  117,  125,
      119,  119,  117,  126,  126,  119,  117,  126,  126,  119,
      127,  127,  127,  127,  119,  117,  119,  126,  128,  128,
      128,  128,  128,  128,  128,  128,  128,  128,  128,  128,
      128,  128,  128,  119,  119,  119,  126,  128,  128,  128,
      128,  128,  128,  128,  128,  128,  128,  128,  128,  128,
      119,  119,  126,  108,  143,  143,  109,  110,  110,  143,
      143,  110,  110,  143,  143,  143,  143,  143,  143,  143,
      143,  110,  143,  143,  143,  143,  143,  143,  143,  143,
      143,  143,  143,  143,  143,  143,  143,  143,  143,  143,

      110,  143,  143,  143,  143,  143,  143,  143,  143,  143,
      143,  143,  143,  143,  143,  113,  110,  108,  143,  143,
      109,  110,  110,  143,  143,  110,  110,  143,  143,  143,
      143,  143,  143,  143,  143,  110,  143,  143,  143,  143,
      143,  143,  143,  143,  143,  143,  143,  143,  143,  143,
      143,  143,  143,  143,  110,  143,  143,  143,  143,  143,
      143,  143,  143,  143,  143,  143,  143,  143,  143,  113,
      110,  108,  143,  143,  109,  110,  110,  143,  143,  110,
      110,  143,  111,  111,  111,  111,  143,  143,  143,  110,
      143,  143,  143,  143,  143,  143,  143,  143,  143,  143,

      143,  143,  143,  143,  143,  143,  143,  143,  110,  143,
      143,  143,  143,  143,  143,  143,  143,  143,  143,  143,
      143,  143,  143,  113,  110,  119,  119,  119,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      143,  143,  143,  143,  119,  119,  119,  119,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  117,  118,  143,
      117,  125,  119,  119,  117,  135,  135,  119,  117,  135,
      135,  119,  136,  136,  136,  136,  119,  117,  119,  135,
      136,  136,  136,  136,  136,  136,  136,  136,  136,  136,
      136,  136,  136,  136,  136,  119,  119,  119,  135,  136,

      136,  136,  136,  136,  136,  136,  136,  136,  136,  136,
      136,  136,  119,  119,  135,  127,  127,  127,  127,  127,
      127,  127,  127,  127,  127,  127,  127,  127,  127,  127,
      143,  143,  143,  143,  127,  127,  127,  127,  127,  127,
      127,  127,  127,  127,  127,  127,  127,  137,  143,  143,
      143,  138,  138,  143,  143,  138,  138,  143,  139,  139,
      139,  139,  143,  143,  143,  138,  143,  143,  143,  143,
      143,  143,  143,  143,  143,  143,  143,  143,  143,  143,
      143,  143,  143,  143,  138,  143,  143,  143,  143,  143,
      143,  143,  143,  143,  143,  143,  143,  143,  143,  113,

      138,  137,  143,  143,  143,  138,  138,  143,  143,  138,
      138,  143,  143,  143,  143,  143,  143,  143,  143,  138,
      143,  143,  143,  143,  143,  143,  143,  143,  143,  143,
      143,  143,  143,  143,  143,  143,  143,  143,  138,  143,
      143,  143,  143,  143,  143,  143,  143,  143,  143,  143,
      143,  143,  143,  113,  138,  137,  143,  143,  143,  138,
      138,  143,  143,  138,  138,  143,  143,  143,  143,  143,
      143,  143,  143,  138,  143,  143,  143,  143,  143,  143,
      143,  143,  143,  143,  143,  143,  143,  143,  143,  143,
      143,  143,  138,  143,  143,  143,  143,  143,  143,  143,

      143,  143,  143,  143,  143,  143,  143,  113,  138,  137,
      143,  143,  143,  138,  138,  143,  143,  138,  138,  143,
      139,  139,  139,  139,  143,  143,  143,  138,  143,  143,
      143,  143,  143,  143,  143,  143,  143,  143,  143,  143,
      143,  143,  143,  143,  143,  143,  138,  143,  143,  143,
      143,  143,  143,  143,  143,  143,  143,  143,  143,  143,
      143,  113,  138,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   42,  143,  143,
       42,  143,   42,   42,   42,   43,   43,   43,   43,   43,
       43,   43,   43,   43,   43,   43,   43,   43,   53,  143,

       53,   53,   76,  143,  143,   76,  143,   76,   76,   76,
       76,   79,  143,  143,   79,  143,   79,   79,   79,   41,
      143,  143,   41,  143,   41,   41,   41,   86,   86,   86,
       86,   86,   86,   59,  143,  143,   59,  143,   59,   59,
       59,   59,   59,   59,   59,   59,  107,  143,  143,  107,
      143,  107,  107,  107,   75,  143,  143,   75,  143,   75,
       75,   75,   75,  112,  112,  143,  112,  143,  112,  112,
      112,  143,  112,   91,   91,  143,   91,   91,   91,   91,
       91,   91,   91,   91,   91,   91,   91,  130,  143,  143,
      130,  143,  130,  130,  130,  111,  111,  143,  111,  143,

      111,  111,  111,  143,  111,  117,  117,  143,  117,  117,
      117,  117,  117,  117,  117,  117,  117,  117,  117,  140,
      143,  143,  140,  143,  140,  140,  140,  143,  140,  142,
      143,  143,  142,  143,  142,  142,  142,  139,  143,  143,
      139,  143,  139,  139,  139,  143,  139,    9,  143,  143,
      143,  143,  143,  143,  143,  143,  143,  143,  143,  143,
      143,  143,  143,  143,  143,  143,  143,  143,  143,  143,
      143,  143,  143,  143,  143,  143,  143,  143,  143,  143,
      143,  143,  143,  143,  143,  143,  143,  143,  143,  143,
      143,  143,  143,  143,  143,  143,  143,  143,  143,  143,

      143,  143,  143,  143,  143,  143
    } ;

static yyconst flex_int16_t yy_chk[2107] =
    {   0,
        0,    1,    1,    1,    1,   15,   38,    0,   15,   38,
       47,   47,   47,   19,   84,   19,   19,   19,   19,    5,
        6,    5,    6,    8,   52,    8,   21,   21,   21,   21,
       24,   22,   24,   24,   24,   24,   56,   56,    1,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    3,    3,    3,

        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,

        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    7,    7,    7,    7,   17,   17,   27,
       28,   17,   29,   30,   32,   33,   58,   34,   35,   58,
       61,    7,   59,    7,   95,   59,   63,   28,   27,   29,
       18,   30,   33,   32,   34,   13,   35,   61,   88,   88,
        7,   16,   95,   63,   17,   16,   16,   43,   43,   16,
       16,   43,   16,   16,   16,   16,   39,  145,  145,   16,
       39,   39,    9,  104,   39,   39,   82,   40,   82,  152,
      152,   40,   40,    0,   39,   40,   40,    0,   16,   44,
       44,  104,    0,   44,   43,   40,   45,   45,   64,  115,

       45,   69,    0,   39,   16,   23,    0,   23,   23,   23,
       23,    0,   71,  121,   40,   64,   23,  115,   69,   39,
       49,   49,   49,   49,   72,   90,   44,   99,   23,   71,
       40,  121,    0,   45,   50,   23,   50,   50,   50,   50,
        0,   72,   90,    0,   99,   23,   26,  154,  154,   26,
       26,   26,    0,   26,   26,   26,    0,   26,   26,   26,
       26,   26,   26,   26,   26,    0,   26,   26,   26,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   26,

       26,   26,   26,   31,  161,  161,   31,   31,   31,    0,
       31,   31,   31,    0,   31,   31,   31,   31,   31,   31,
       31,   31,    0,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       37,    0,   80,   80,   37,   37,   80,    0,   37,   37,
        0,   37,   37,   37,   37,   41,    0,    0,   37,   41,
       41,    0,    0,   41,   41,    0,    0,   51,   51,   51,
       51,    0,    0,   41,    0,    0,   37,   37,   51,   80,

        0,    0,    0,   54,   54,   54,   54,  114,  114,  114,
      114,    0,   41,   37,   54,   55,   51,   55,   55,   55,
       55,  132,  132,  132,  132,    0,    0,    0,   41,   42,
        0,    0,   54,   42,   42,    0,    0,   42,   42,    0,
       42,   42,   42,   42,   73,    0,    0,   42,   73,   73,
        0,    0,   73,   73,    0,  108,    0,    0,    0,  108,
      108,    0,   73,  108,  108,    0,   42,   87,   87,   87,
       87,    0,    0,  108,    0,    0,    0,    0,   87,    0,
        0,   73,   42,   53,    0,   53,   53,   53,   53,   53,
       53,   53,  108,    0,    0,    0,   87,   73,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,  108,    0,
        0,    0,    0,    0,   53,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       53,   62,   62,    0,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   65,
        0,    0,   65,   65,   65,    0,   65,   65,   65,    0,

       65,   65,   65,   65,   65,   65,   65,   65,    0,   65,
       65,   65,   65,   65,   65,   65,   65,   65,   65,   65,
       65,   65,   65,   65,   65,   65,   65,   65,   65,   65,
       65,   65,   65,   65,   65,   65,   65,   65,   65,   65,
       65,   65,   65,   65,   65,   65,   66,    0,    0,   66,
       66,   66,    0,   66,   66,   66,    0,   66,   66,   66,
       66,   66,   66,   66,   66,    0,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,

       66,   66,   66,   70,   70,    0,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   74,    0,  137,    0,   74,   74,  137,  137,   74,
       74,  137,  137,    0,    0,    0,    0,    0,    0,   74,
        0,  137,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   74,   74,    0,

      137,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   74,   75,  137,    0,    0,   75,
       75,    0,    0,   75,   75,    0,    0,    0,    0,    0,
        0,    0,    0,   75,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   75,   75,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   75,   76,
        0,    0,    0,   76,   76,    0,    0,   76,   76,    0,
       76,   76,   76,   76,    0,    0,    0,   76,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,   76,   76,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   76,   81,    0,    0,   81,   81,   81,    0,
        0,   81,   81,    0,   81,   81,   81,   81,    0,    0,
        0,   81,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       81,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   81,   81,   83,    0,   83,
       83,   83,   83,   83,   83,   83,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,   83,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   83,   92,   92,   92,   92,   92,
       92,   92,   92,   92,   92,   92,   92,   92,   92,   92,
        0,    0,    0,    0,   92,   92,   92,   92,   92,   92,
       92,   92,   92,   92,   92,   92,   92,   96,   96,    0,
       96,   96,   96,   96,   96,   96,   96,   96,   96,   96,
       96,   96,   96,   96,   96,   96,   96,   96,   96,   96,
       96,   96,   96,   96,   96,   96,   96,   96,   96,   96,
       96,   96,   96,   96,   96,   96,   96,   96,   96,   96,

       96,   96,   96,   96,   96,   96,   96,   96,   96,   96,
       96,   96,   96,   96,   96,  100,  100,    0,  100,  100,
      100,  100,  100,  100,  100,  100,  100,  100,  100,  100,
      100,  100,  100,  100,  100,  100,  100,  100,  100,  100,
      100,  100,  100,  100,  100,  100,  100,  100,  100,  100,
      100,  100,  100,  100,  100,  100,  100,  100,  100,  100,
      100,  100,  100,  100,  100,  100,  100,  100,  100,  100,
      100,  100,  100,  101,  101,  101,  101,  101,  101,  101,
      101,  101,  101,  101,  101,  101,  101,  101,    0,    0,
        0,    0,  101,  101,  101,  101,  101,  101,  101,  101,

      101,  101,  101,  101,  101,  105,  105,    0,  105,  105,
      105,  105,  105,  105,  105,  105,  105,  105,  105,  105,
      105,  105,  105,  105,  105,  105,  105,  105,  105,  105,
      105,  105,  105,  105,  105,  105,  105,  105,  105,  105,
      105,  105,  105,  105,  105,  105,  105,  105,  105,  105,
      105,  105,  105,  105,  105,  105,  105,  105,  105,  105,
      105,  105,  105,  110,    0,    0,  110,  110,  110,    0,
        0,  110,  110,    0,    0,    0,    0,    0,    0,    0,
        0,  110,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

      110,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,  110,  110,  111,    0,    0,
      111,  111,  111,    0,    0,  111,  111,    0,    0,    0,
        0,    0,    0,    0,    0,  111,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  111,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,  111,
      111,  112,    0,    0,  112,  112,  112,    0,    0,  112,
      112,    0,  112,  112,  112,  112,    0,    0,    0,  112,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,  112,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,  112,  112,  118,  118,  118,  118,  118,
      118,  118,  118,  118,  118,  118,  118,  118,  118,  118,
        0,    0,    0,    0,  118,  118,  118,  118,  118,  118,
      118,  118,  118,  118,  118,  118,  118,  125,  125,    0,
      125,  125,  125,  125,  125,  125,  125,  125,  125,  125,
      125,  125,  125,  125,  125,  125,  125,  125,  125,  125,
      125,  125,  125,  125,  125,  125,  125,  125,  125,  125,
      125,  125,  125,  125,  125,  125,  125,  125,  125,  125,

      125,  125,  125,  125,  125,  125,  125,  125,  125,  125,
      125,  125,  125,  125,  125,  126,  126,  126,  126,  126,
      126,  126,  126,  126,  126,  126,  126,  126,  126,  126,
        0,    0,    0,    0,  126,  126,  126,  126,  126,  126,
      126,  126,  126,  126,  126,  126,  126,  131,    0,    0,
        0,  131,  131,    0,    0,  131,  131,    0,  131,  131,
      131,  131,    0,    0,    0,  131,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  131,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,  131,

      131,  138,    0,    0,    0,  138,  138,    0,    0,  138,
      138,    0,    0,    0,    0,    0,    0,    0,    0,  138,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,  138,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,  138,  138,  139,    0,    0,    0,  139,
      139,    0,    0,  139,  139,    0,    0,    0,    0,    0,
        0,    0,    0,  139,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  139,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,  139,  139,  140,
        0,    0,    0,  140,  140,    0,    0,  140,  140,    0,
      140,  140,  140,  140,    0,    0,    0,  140,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,  140,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,  140,  140,  144,  144,  144,  144,  144,  144,  144,
      144,  144,  144,  144,  144,  144,  144,  146,    0,    0,
      146,    0,  146,  146,  146,  147,  147,  147,  147,  147,
      147,  147,  147,  147,  147,  147,  147,  147,  148,    0,

      148,  148,  149,    0,    0,  149,    0,  149,  149,  149,
      149,  150,    0,    0,  150,    0,  150,  150,  150,  151,
        0,    0,  151,    0,  151,  151,  151,  153,  153,  153,
      153,  153,  153,  155,    0,    0,  155,    0,  155,  155,
      155,  155,  155,  155,  155,  155,  156,    0,    0,  156,
        0,  156,  156,  156,  157,    0,    0,  157,    0,  157,
      157,  157,  157,  158,  158,    0,  158,    0,  158,  158,
      158,    0,  158,  159,  159,    0,  159,  159,  159,  159,
      159,  159,  159,  159,  159,  159,  159,  160,    0,    0,
      160,    0,  160,  160,  160,  162,  162,    0,  162,    0,

      162,  162,  162,    0,  162,  163,  163,    0,  163,  163,
      163,  163,  163,  163,  163,  163,  163,  163,  163,  164,
        0,    0,  164,    0,  164,  164,  164,    0,  164,  165,
        0,    0,  165,    0,  165,  165,  165,  166,    0,    0,
      166,    0,  166,  166,  166,    0,  166,  143,  143,  143,
      143,  143,  143,  143,  143,  143,  143,  143,  143,  143,
      143,  143,  143,  143,  143,  143,  143,  143,  143,  143,
      143,  143,  143,  143,  143,  143,  143,  143,  143,  143,
      143,  143,  143,  143,  143,  143,  143,  143,  143,  143,
      143,  143,  143,  143,  143,  143,  143,  143,  143,  143,

      143,  143,  143,  143,  143,  143
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[17] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,     };

extern int yy_flex_debug;
int yy_flex_debug = 0;

static yy_state_type *yy_state_buf=0, *yy_state_ptr=0;
static char *yy_full_match;
static int yy_lp;
static int yy_looking_for_trail_begin = 0;
static int yy_full_lp;
static int *yy_full_state;
#define YY_TRAILING_MASK 0x2000
#define YY_TRAILING_HEAD_MASK 0x4000
#define REJECT \
{ \
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */ \
yy_cp = (yy_full_match); /* restore poss. backed-over text */ \
(yy_lp) = (yy_full_lp); /* restore orig. accepting pos. */ \
(yy_state_ptr) = (yy_full_state); /* restore orig. state */ \
yy_current_state = *(yy_state_ptr); /* restore curr. state */ \
++(yy_lp); \
goto find_rule; \
}

#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer.lex"
#line 2 "lexer.lex"

/* Declarations section */
#include <stdio.h>
#include <stdlib.h> //for strtol
#include <ctype.h> //for isxdigit
#include <string.h> //for strcmp
#include "tokens.h"

typedef enum tokens tokens_t;
tokens_t showToken(const char* name);
void showTokenStr(char* name);
void showTokenInt(char* name);
void showTokenComm(char* name);


#line 1043 "lex.yy.c"

#define INITIAL 0
#define KA 1
#define IN 2
#define K 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		unsigned n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 50 "lexer.lex"

#line 1233 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

        /* Create the reject buffer large enough to save one state per allowed character. */
        if ( ! (yy_state_buf) )
            (yy_state_buf) = (yy_state_type *)yyalloc(YY_STATE_BUF_SIZE  );
            if ( ! (yy_state_buf) )
                YY_FATAL_ERROR( "out of dynamic memory in yylex()" );

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();

		(yy_state_ptr) = (yy_state_buf);
		*(yy_state_ptr)++ = yy_current_state;

yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 144 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*(yy_state_ptr)++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 2048 );

yy_find_action:
		yy_current_state = *--(yy_state_ptr);
		(yy_lp) = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( (yy_lp) && (yy_lp) < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[(yy_lp)];
				if ( yy_act & YY_TRAILING_HEAD_MASK ||
				     (yy_looking_for_trail_begin) )
					{
					if ( yy_act == (yy_looking_for_trail_begin) )
						{
						(yy_looking_for_trail_begin) = 0;
						yy_act &= ~YY_TRAILING_HEAD_MASK;
						break;
						}
					}
				else if ( yy_act & YY_TRAILING_MASK )
					{
					(yy_looking_for_trail_begin) = yy_act & ~YY_TRAILING_MASK;
					(yy_looking_for_trail_begin) |= YY_TRAILING_HEAD_MASK;
					}
				else
					{
					(yy_full_match) = yy_cp;
					(yy_full_state) = (yy_state_ptr);
					(yy_full_lp) = (yy_lp);
					break;
					}
				++(yy_lp);
				goto find_rule;
				}
			--yy_cp;
			yy_current_state = *--(yy_state_ptr);
			(yy_lp) = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					   
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 51 "lexer.lex"
{ BEGIN(K); return(KEY);}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 52 "lexer.lex"
{BEGIN(KA); return(ASSIGN); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 53 "lexer.lex"
{return(SECTION);}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 54 "lexer.lex"
{BEGIN(IN); return(INDENT);}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(KA):
case YY_STATE_EOF(IN):
case YY_STATE_EOF(K):
#line 55 "lexer.lex"
{return(EOF);}  //todo: fit this . shani
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 56 "lexer.lex"
{return(TRUE);}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 57 "lexer.lex"
{return(FALSE);}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 58 "lexer.lex"
{return(INTEGER);}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 59 "lexer.lex"
{return(REAL);}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 60 "lexer.lex"
{return(PATH);}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 61 "lexer.lex"
{return(LINK);}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 62 "lexer.lex"
{return(SEP);}
	YY_BREAK
case 12:
/* rule 12 can match eol */
YY_RULE_SETUP
#line 63 "lexer.lex"
{return(STRING);}
	YY_BREAK
case 13:
/* rule 13 can match eol */
YY_RULE_SETUP
#line 64 "lexer.lex"
BEGIN(0);
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 65 "lexer.lex"
;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 66 "lexer.lex"
{printf("Error %c\n", yytext[yyleng-1]);
return(0);} //todo check if ok shani
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 69 "lexer.lex"
ECHO;
	YY_BREAK
#line 1446 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	(yy_state_ptr) = (yy_state_buf);
	*(yy_state_ptr)++ = yy_current_state;

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 144 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*(yy_state_ptr)++ = yy_current_state;
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    
	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 144 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 143);
	if ( ! yy_is_jam )
		*(yy_state_ptr)++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');
	if ( YY_CURRENT_BUFFER_LVALUE->yy_at_bol )
		   
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_state_buf) = 0;
    (yy_state_ptr) = 0;
    (yy_full_match) = 0;
    (yy_lp) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    yyfree ( (yy_state_buf) );
    (yy_state_buf)  = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 69 "lexer.lex"


/*
int NameToToken(const char* name){
    const char* convert[]={"KEY","SECTION","INDENT","ASSIGN","TRUE","FALSE","INTEGER","REAL","STRING","PATH","LINK","SEP","EOF"};
    int i=0;
    for(i=(int)KEY; i<((int)EF+1); i++){
        if (strcmp(name,convert[i]))
            return i;
    }
    return -1; //we shouldnt reach here
}

tokens_t showToken(const char*  name)
{
    tokens_t to_return = (tokens_t)(NameToToken(name));
    return to_return;
}


void NonBlockedStrHandle(char* n_yytext){
    //this function copies the string as it is
    int i=0;
    while(i != yyleng){
        n_yytext[i]=yytext[i];
        i++;
    }
    //deleteTrailingSpaces(yytext,n_yytext,yyleng);	//racheli
}

void BlockedStrHandle(int leng, char* yytext_t,char* n_yytext){
    int i=1;
    int j=0;
    while(yytext_t[i] != '"'){
        if (i == leng){
            //the input limit reached but no '"' detected
            printf("Error unclosed string\n");
            //exit(0);
        }
        if (yytext_t[i] == '\\'){
            i++; //skip the "\"
            if (i==leng){
                // \ is at the end of the string
                printf("Error %c\n", '\\');
              //  exit(0);
            }
            if (yytext_t[i] == 'x' || yytext_t[i] == 'X'){
                char *ptr;
                char hexVal[2];
                hexVal[0] = yytext_t[i+1];
                hexVal[1] = yytext_t[i+2];
                //strtol converts string to int. "16" is for hex value
                int decVal = (int)strtol(hexVal, &ptr, 16);
                if (decVal<0 || decVal > 255 || !isxdigit(hexVal[0]) ||!isxdigit(hexVal[1])){
                    // \xdd - but dd is not a valid ascii value
                    printf("Error undifined escape sequence %c\n", yytext_t[i]);
                //    exit(0);
                }
                else{
                    char c = decVal; //converts int ascii value into it's suitiable char
                    n_yytext[j] = c;
                    i+=3; j++;
                }
            }
            else{
                if(((yytext_t[i]=='\r') && yytext_t[i+1]=='\n')){
                    n_yytext[j]='\r';
                    n_yytext[j+1]='\n';
                    j+=2; i++;
                    continue;
                }
                //escape seqence is not x
                switch(yytext_t[i]){
                    case 't':
                    case 'T':
                        n_yytext[j]='\t';
                        j++; i++;
                        break;
                    case '\\':
                        n_yytext[j]='\\';
                        j++;; i++;
                        break;
                    case '"':
                        n_yytext[j]='\"';
                        j++; i++;
                        break;
                    case 'r':
                    case 'R':
                        n_yytext[j]='\r';
                        j++; i++;
                        break;
                    case ';':
                        n_yytext[j]=';'; //todo: test chars: : ; =
                        j++; i++;
                        break;
                    case ':':
                        n_yytext[j]=':';
                        j++; i++;
                        break;
                    case '=':
                        n_yytext[j]='=';
                        j++; i++;
                        break;
                    case 'n':
                    case 'N':
                        n_yytext[j]='\n';
                        j++; i++;
                        break;

                    case 'a':
                    case 'A':
                        n_yytext[j]='\a';
                        j++; i++;
                        break;
                    case '0':
                        n_yytext[j]='\0';
                        j++; i++;
                        break;
                    case 'b':
                    case 'B':
                        n_yytext[j]='\b';
                        j++; i++;
                        break;
                    case '#':
                        n_yytext[j]='#';
                        j++; i++;
                        break;
                    default:
                        printf("Error undefined escape sequence %c\n", yytext_t[i]);
                  //      exit(0);
                }
            }
        }
        else{
            n_yytext[j] = yytext_t[i];
            i++; j++;
        }
    }
}

int deleteNewLines(char* yytext_t){
    int i=1;
    int j=1;
    yytext_t[0]='"';
    while(i!=yyleng){
        if((yytext[i]=='\r')&&(yytext[i+1]=='\n')){
            yytext_t[j]='\x20';
            i++;
        }
        else if ((yytext[i]=='\x0A')||(yytext[i]=='\x0D')){
            yytext_t[j]='\x20';
        }
        else{
            yytext_t[j] = yytext[i];
        }
        i++; j++;
    }
    return j;
}

void showTokenStr(char*  name)
{
    char n_yytext[1024]={0};
    //a blocked string will allwase start with "
    if (yytext[0] == '"'){
        char yytext_t[1024]={0};
        int leng = deleteNewLines(yytext_t);
        BlockedStrHandle(leng, yytext_t,n_yytext);
    }
    else
        NonBlockedStrHandle(n_yytext);

    showToken(n_yytext);
}

void showTokenInt(char*  name)
{
    long decVal =0;
    char* ptr;
    if (yytext[0] == '0'){
        if(yytext[1] == 'x' || yytext[1] == 'X'){
            //the number is hexdecimal
            decVal = strtol(yytext, &ptr, 0);
        }
        else if (yytext[1]=='b' || yytext[1]=='B'){
            //the number is binary
            decVal = strtol((yytext+2), &ptr, 2);
        }
        else{
            //try to convert to octal. convertion will succeed only if there is only digits from the range 0-8
            decVal = strtol(yytext, &ptr, 8);
            if (decVal == 0 && yyleng!=1){
                //convertion failed, the number is not octal, therefor, it is a decimal that starts with "0"
                decVal = strtol(yytext, &ptr, 10);
            }
        }

    }
    else{
        //the number is decimal
        decVal = strtol(yytext, &ptr, 10);
    }
   showToken(name);
}

void showTokenComm(char*  name)
{
    int temp = yylineno;
    char n_yytext[1024]={0};
    int i=0;
    int j=0;
    while((yytext[i]!='#')&&(yytext[i]!=';')){
        i++;
    }
    //delete Trailing Spaces
    int index=0;
    int index_t=yyleng-1;
    while(yytext[index_t]=='\t' || yytext[index_t]=='\x20'){
        index_t--;
    }
    while(i!=index_t+1){
        n_yytext[j]=yytext[i];
        i++; j++;
    }
    printf("%d %s %s\n",temp, name, n_yytext);
}
*/
